[workspace]
resolver = "2"
members = [
    "2015",
    "2018",
    "2019/aoc_rust",
    "2020/01",
    "2021/_1",
    "2021/_2",
    "2021/_3",
    "2021/_4",
    "2021/_5",
    "2021/_6",
    "2021/_7",
    "2022",
    "2025/rust",
    "aoc-rust-common", "runner",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
