[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iter_tools = "0.1.4"
md5 = "0.7.0"
onig = "6.4.0"
regex = "1.8.1"
