[package]
name = "aoc-rust-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
chrono = "0.4"
insta = { version = "1.47.2", features = ["yaml"] }

[dev-dependencies]
divan = "0.1.21"
insta = { version = "1.47.2", features = ["yaml"] }

[[bench]]
name = "main"
harness = false

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(advent_of_code_ci)'] }
