[package]
name = "_1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

aoc-rust-common = { path = "../../aoc-rust-common" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(advent_of_code_ci)'] }
