[package]
name = "runner"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-rust-common = { path = "../aoc-rust-common" }
aoc_2015 = { path = "../2015" }
aoc_2018 = { package = "aoc", path = "../2018" }
aoc_rust_2019 = { package = "aoc_rust", path = "../2019/aoc_rust" }
aoc_2020_01 = { package = "first", path = "../2020/01" }
aoc_2021_01 = { package = "_1", path = "../2021/_1" }
aoc_2021_02 = { package = "_2", path = "../2021/_2" }
aoc_2021_03 = { package = "_3", path = "../2021/_3" }
aoc_2021_04 = { package = "_4", path = "../2021/_4" }
aoc_2021_05 = { package = "_5", path = "../2021/_5" }
aoc_2021_06 = { package = "_6", path = "../2021/_6" }
aoc_2021_07 = { package = "_7", path = "../2021/_7" }
aoc_2022 = { path = "../2022" }
aoc_2025 = { path = "../2025/rust" }
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
